config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new, :edit] do
    collection do
      post 'login'
      get 'generate_access_token'
    end
  end

  get "auth/:provider/callback", to: 'users#google_login'
  get 'auth/failure', to: redirect('/')

  post 'password/forgot', to: 'passwords#forgot'

  root to: "users#index"

  resources :invites, only: [:index, :create]
  resources :roles, only: [:index, :show, :create, :destroy, :update]
end

app/controllers/invites_controller.rb
class InvitesController < ActionController::Base
  require "reset"

  def index
    user = load_user
    token = params[:token].to_s
    if user.present? && user.confirmation_token_valid?(token)
      @show_form = true
    end
  end

  def create
    if params[:broken]
      @response = Reset.new.forgot_password(params)
      render("index") && return
    end
    reset = Reset.new
    user = reset.get_user(params[:token].to_s)
    @response = reset.reset_password(params)
    @token = params[:token]
    @show_form = true unless @response[:json][:error] == Message.invalid_token
    if @response[:json][:status] == Message.success
      domain = user.roles.pluck(:domain).last
      redirect_to(domain)
    else
      render "index"
    end
  end

  private

  def load_user
    token = params[:token].to_s
    user = (Reset.new.get_user(params[:token]) unless token.blank?)
    user
  end
end

app/views/invites/index.html.erb
<!DOCTYPE html>
<html>
   <head>
      <meta name="viewport" content="width=device-width,height=device-height initial-scale=1">
      <%= favicon_link_tag 'favicon.ico' %>
      <title>Andela - Guest Service</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
      <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.0/css/mdb.min.css" rel="stylesheet">
      <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.0/js/mdb.min.js"></script>
      <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
      <style>
         html,
         body{
         background-color: #f4f8f9;
         text-align: center;
         }
         #message {
         <% if @response %>
         color: <% if @response[:json][:linkSent].blank? %>
         #F44336;
         <%else%>
         #34D027;
         <%end%>
         <% end %>
         padding: 1em;
         text-align:center;
         font-size: 12px;
         font-family: sans-serif;
         font-weight: 100;
         margin-top: 3em;
         }
         .myForm {
         display: inline-block;
         margin: 0 auto;
         transform: translateY(50%);
         width: 35rem;
         padding: 4.4rem;
         border-radius: 4px;
         background-color: #fff;
         text-align: left;
         }
         .form-control {
         margin-bottom: 15px !important;
         }
         .btn-indigo {
         float: right;
         margin: 0;
         width: 100%;
         background-color: #3459db !important;
         }
         .brand {
         height: 30px;
         }
         .main-container {
         float: left;
         position: relative;
         left: 50%;
         }
         .fixer-container {
         float: left;
         position: relative;
         left: -50%;
         }
         label {
         font-size: 12px !important;
         }
      </style>
   </head>
   <body>
      <%= render("layouts/header") %>
      <% if @show_form %>
      <%= form_with url: invites_path, class: "myForm" do |form| %>
      <div class="main-container">
         <div class="fixer-container"><%= image_tag "logo2.png", class: "brand", alt:"logo"%>
            Andela Guest Service
         </div>
      </div>
      <div id='message'>
         <% if @response %>
         <div><%= @response[:json][:error] %></div>
         <div><%= @response[:json][:linkSent] %></div>
         <div><%= @response[:json][:status] %></div>
         <% end %>
      </div>
      <%= form.label :password, "New password", class: "grey-text"%>
      <%= form.text_field :password, class:"form-control", type: "password", :required => true %>
      <%= form.label :password_confirmation, "Confirm password", class: "grey-text"%>
      <%= form.text_field :password_confirmation, class:"form-control", type: "password", :required => true %>
      <% if @token.blank? %>
      <%= hidden_field_tag :token, params[:token] %>
      <% else %>
      <%= hidden_field_tag :token, @token %>
      <% end %>
      <%= form.submit "Submit", class:"btn btn-indigo" %>
      <% end %>
      <% else %>
      <%= form_with url: invites_path, class: "myForm" do |form| %>
      <div class="main-container">
         <div class="fixer-container"><%= image_tag "logo2.png", class: "brand", alt:"logo"%>
            Andela Guest Service
         </div>
      </div>
      <div id='message'>
         <% if @response %>
         <div><%= @response[:json][:error] %></div>
         <div><%= @response[:json][:linkSent] %></div>
         <div><%= @response[:json][:status] %></div>
         <% end %>
      </div>
      <%= form.label :email, "Email address", class: "grey-text"%>
      <%= form.text_field :email, class:"form-control", type: "email", :required => true %>
      <%= hidden_field_tag :broken, true %>
      <%= form.submit "Submit", class:"btn btn-indigo" %>
      <% end %>
      <%end%>
      <%= render("layouts/footer") %>
   </body>
</html>